use std::{
    collections::{BTreeMap, HashSet},
    fs,
    net::TcpListener,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, Result, bail};

use crate::{
    config::{Config, parse_port_spec},
    detection::{git, nul_paths},
};

const PROCESS_ENV: &str = ".wt.env";

pub struct Assignment {
    pub key: String,
    original: u16,
    assigned: u16,
    process: bool,
}

pub struct Prepared {
    pub assignments: Vec<Assignment>,
    pub copied_files: BTreeMap<PathBuf, String>,
    /// Configured copy paths without a source; bootstrap may generate them.
    pub pending: Vec<PathBuf>,
}

impl Prepared {
    pub fn ports(&self) -> BTreeMap<String, u16> {
        self.assignments
            .iter()
            .map(|assignment| (assignment.key.clone(), assignment.assigned))
            .collect()
    }
}

pub fn prepare(
    config: &Config,
    source: &Path,
    target: &Path,
    compose_name: &str,
    used_ports: &HashSet<u16>,
) -> Result<Prepared> {
    reject_tracked_paths(config, target)?;
    let (mut copied, pending) = copy_files(config, source, target)?;
    let assignments = assign_ports(config, source, used_ports)?;
    if !assignments.is_empty() {
        for path in &copied {
            rewrite_file(&target.join(path), &assignments)?;
        }
    }
    if writes_process_env(config, source, &assignments) {
        write_process_env(target, &assignments, config.compose.then_some(compose_name))?;
        copied.push(PathBuf::from(PROCESS_ENV));
    }
    if config.compose {
        let env = config.env.as_ref().context("wt.compose requires wt.env")?;
        // A missing env file may still be generated by bootstrap; see `complete`.
        if copied.contains(env) {
            set_value(&target.join(env), "COMPOSE_PROJECT_NAME", compose_name)?;
        }
    }
    let copied_files = fingerprints(target, &copied)?;
    Ok(Prepared {
        assignments,
        copied_files,
        pending,
    })
}

/// Records configured paths that bootstrap generated and rewrites their ports.
/// Returns the paths that are still missing.
pub fn complete(
    config: &Config,
    target: &Path,
    compose_name: &str,
    assignments: &[Assignment],
    pending: &[PathBuf],
    copied_files: &mut BTreeMap<PathBuf, String>,
) -> Result<Vec<PathBuf>> {
    let mut missing = Vec::new();
    for relative in pending {
        let entries = expand(target, relative)?;
        if entries.is_empty() {
            missing.push(relative.clone());
            continue;
        }
        for entry in entries {
            if copied_files.contains_key(&entry) {
                continue;
            }
            if !assignments.is_empty() {
                rewrite_file(&target.join(&entry), assignments)?;
            }
            // A generated primary env file still needs its Compose project.
            if config.compose && Some(&entry) == config.env.as_ref() {
                set_value(&target.join(&entry), "COMPOSE_PROJECT_NAME", compose_name)?;
            }
            let hash = fingerprint(target, &entry)?;
            copied_files.insert(entry, hash);
        }
    }
    Ok(missing)
}

fn reject_tracked_paths(config: &Config, target: &Path) -> Result<()> {
    let mut paths = config.copied_files();
    paths.extend(config.disposable.iter().cloned());
    if config.ports.iter().any(|port| port.contains(':')) {
        paths.push(PathBuf::from(PROCESS_ENV));
    }
    if paths.is_empty() {
        return Ok(());
    }
    let output = Command::new("git")
        .current_dir(target)
        .args(["ls-files", "-z", "--"])
        .args(paths.iter().map(|path| pathspec(path)))
        .output()
        .context("check configured paths with git")?;
    if !output.status.success() {
        bail!(
            "cannot inspect configured paths: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    if let Some(path) = output
        .stdout
        .split(|byte| *byte == 0)
        .find(|path| !path.is_empty())
    {
        bail!(
            "configured path is tracked by Git and must not be copied or discarded: {}",
            String::from_utf8_lossy(path)
        );
    }
    Ok(())
}

/// Copies configured files, directories, and glob matches, then ignored
/// `.local` files. Returns the copied entries and configured paths that have
/// no source yet.
fn copy_files(
    config: &Config,
    source: &Path,
    target: &Path,
) -> Result<(Vec<PathBuf>, Vec<PathBuf>)> {
    let mut copied = Vec::new();
    let mut pending = Vec::new();
    for relative in config.copied_files() {
        let entries = expand(source, &relative)?;
        if entries.is_empty() {
            pending.push(relative);
            continue;
        }
        for entry in entries {
            if !copied.contains(&entry) {
                copy_entry(source, target, &entry)?;
                copied.push(entry);
            }
        }
    }
    // Ignored `.local` files are private per-checkout settings, so every
    // worktree gets them. Existing paths, e.g. tracked ones, are never replaced.
    for relative in ignored_local_files(source)? {
        let exists = fs::symlink_metadata(target.join(&relative)).is_ok();
        if source.join(&relative).is_file() && !exists && !copied.contains(&relative) {
            copy_entry(source, target, &relative)?;
            copied.push(relative);
        }
    }
    Ok((copied, pending))
}

/// Resolves a configured path in `root` to the regular files it stands for:
/// the file itself, every file below a directory, or the untracked matches of
/// a glob such as `**/*.pem`. Missing paths resolve to nothing.
pub fn expand(root: &Path, relative: &Path) -> Result<Vec<PathBuf>> {
    if is_glob(relative) {
        return glob_matches(root, relative);
    }
    let path = root.join(relative);
    let Ok(metadata) = fs::symlink_metadata(&path) else {
        return Ok(Vec::new());
    };
    if metadata.is_dir() {
        let mut files = Vec::new();
        collect_files(root, relative, &mut files)?;
        return Ok(files);
    }
    if metadata.is_file() || path.is_file() {
        return Ok(vec![relative.to_owned()]);
    }
    bail!(
        "copy source must be a regular file, directory, or glob: {}",
        relative.display()
    );
}

fn collect_files(root: &Path, relative: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    let directory = root.join(relative);
    let mut entries = fs::read_dir(&directory)
        .with_context(|| format!("read {}", directory.display()))?
        .collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let child = relative.join(entry.file_name());
        let metadata = entry.metadata()?;
        if metadata.is_dir() && !entry.file_type()?.is_symlink() {
            collect_files(root, &child, files)?;
        } else if metadata.is_file() {
            files.push(child);
        }
    }
    Ok(())
}

fn is_glob(path: &Path) -> bool {
    path.to_string_lossy().contains(['*', '?', '['])
}

fn glob_matches(root: &Path, pattern: &Path) -> Result<Vec<PathBuf>> {
    let spec = pathspec(pattern);
    let mut matches = Vec::new();
    for ignored in [false, true] {
        let mut args = vec!["ls-files", "--others", "--exclude-standard", "-z"];
        if ignored {
            args.push("--ignored");
        }
        args.extend(["--", &spec]);
        let output = Command::new("git")
            .current_dir(root)
            .args(&args)
            .output()
            .context("expand copy glob with git")?;
        if !output.status.success() {
            bail!(
                "cannot expand {}: {}",
                pattern.display(),
                String::from_utf8_lossy(&output.stderr).trim()
            );
        }
        for path in nul_paths(&output.stdout)? {
            if root.join(&path).is_file() && !matches.contains(&path) {
                matches.push(path);
            }
        }
    }
    matches.sort();
    Ok(matches)
}

fn pathspec(path: &Path) -> String {
    if is_glob(path) {
        format!(":(glob){}", path.display())
    } else {
        path.display().to_string()
    }
}

/// Copies one file. A symlink whose target lies outside the repository is
/// recreated as the same symlink, so private files such as notes linked from
/// a dotfiles directory stay shared. Other symlinks are copied as content.
fn copy_entry(source: &Path, target: &Path, relative: &Path) -> Result<()> {
    let from = source.join(relative);
    let destination = target.join(relative);
    fs::create_dir_all(
        destination
            .parent()
            .context("copy destination has no parent")?,
    )?;
    if let Some(link) = external_link(source, &from)? {
        if fs::symlink_metadata(&destination).is_ok() {
            fs::remove_file(&destination)?;
        }
        #[cfg(unix)]
        std::os::unix::fs::symlink(&link, &destination)
            .with_context(|| format!("link {}", relative.display()))?;
        #[cfg(not(unix))]
        fs::copy(&from, &destination).with_context(|| format!("copy {}", relative.display()))?;
        return Ok(());
    }
    fs::copy(&from, &destination).with_context(|| format!("copy {}", relative.display()))?;
    Ok(())
}

fn external_link(source: &Path, path: &Path) -> Result<Option<PathBuf>> {
    if !fs::symlink_metadata(path)?.file_type().is_symlink() {
        return Ok(None);
    }
    let link = fs::read_link(path)?;
    if !link.is_absolute() {
        return Ok(None);
    }
    let Ok(resolved) = fs::canonicalize(&link) else {
        return Ok(None);
    };
    let repository = fs::canonicalize(source)?;
    Ok((!resolved.starts_with(&repository)).then_some(link))
}

/// `--directory` lists wholly ignored directories such as `node_modules/`
/// without entering them; they are not files and get skipped.
fn ignored_local_files(source: &Path) -> Result<Vec<PathBuf>> {
    let output = git(
        source,
        [
            "ls-files",
            "--others",
            "--ignored",
            "--exclude-standard",
            "--directory",
            "-z",
            "--",
            ":(glob)**/*.local",
            ":(glob)**/*.local.*",
        ],
    )
    .context("find ignored .local files")?;
    nul_paths(&output.stdout)
}

fn assign_ports(
    config: &Config,
    source: &Path,
    used_ports: &HashSet<u16>,
) -> Result<Vec<Assignment>> {
    let env = config
        .env
        .as_ref()
        .map(|path| fs::read_to_string(source.join(path)))
        .transpose()?;
    let mut unavailable = used_ports.clone();
    let mut assigned_by_original = BTreeMap::new();
    let mut result = Vec::new();
    for raw in &config.ports {
        let spec = parse_port_spec(raw)?;
        let original = original_port(config, env.as_deref(), &spec)?;
        let assigned = match assigned_by_original.get(&original) {
            Some(assigned) => *assigned,
            None => available_port(original, &unavailable)?,
        };
        unavailable.insert(assigned);
        assigned_by_original.insert(original, assigned);
        result.push(Assignment {
            key: spec.key,
            original,
            assigned,
            process: spec.default.is_some(),
        });
    }
    Ok(result)
}

fn original_port(
    config: &Config,
    env: Option<&str>,
    spec: &crate::config::PortSpec,
) -> Result<u16> {
    if let Some(default) = spec.default {
        return Ok(default);
    }
    let env_path = config.env.as_ref().context("wt.port requires wt.env")?;
    value(env.context("wt.port requires wt.env")?, &spec.key)
        .with_context(|| format!("{} is missing from {}", spec.key, env_path.display()))?
        .parse::<u16>()
        .with_context(|| format!("{} must be a port number", spec.key))
}

fn available_port(start: u16, unavailable: &HashSet<u16>) -> Result<u16> {
    for candidate in start..=u16::MAX {
        if !unavailable.contains(&candidate) && TcpListener::bind(("127.0.0.1", candidate)).is_ok()
        {
            return Ok(candidate);
        }
    }
    bail!("no free port at or above {start}")
}

fn rewrite_file(path: &Path, assignments: &[Assignment]) -> Result<()> {
    // A shared symlink must keep its target untouched.
    if fs::symlink_metadata(path)?.file_type().is_symlink() {
        return Ok(());
    }
    // Binary files have no ports to rewrite.
    let Ok(original) = String::from_utf8(fs::read(path)?) else {
        return Ok(());
    };
    let mut contents = original.clone();
    for assignment in assignments.iter().filter(|assignment| !assignment.process) {
        contents = replace_value(&contents, &assignment.key, &assignment.assigned.to_string());
    }
    contents = replace_local_ports(contents, assignments)?;
    if contents == original {
        return Ok(());
    }
    fs::write(path, contents).with_context(|| format!("update {}", path.display()))
}

fn replace_local_ports(mut contents: String, assignments: &[Assignment]) -> Result<String> {
    for (index, assignment) in assignments.iter().enumerate() {
        let marker = format!("__WT_ASSIGNED_PORT_{index}__");
        if contents.contains(&marker) {
            bail!("env file contains reserved marker {marker}");
        }
        contents = contents.replace(
            &format!("localhost:{}", assignment.original),
            &format!("localhost:{marker}"),
        );
        contents = contents.replace(
            &format!("127.0.0.1:{}", assignment.original),
            &format!("127.0.0.1:{marker}"),
        );
    }
    for (index, assignment) in assignments.iter().enumerate() {
        contents = contents.replace(
            &format!("__WT_ASSIGNED_PORT_{index}__"),
            &assignment.assigned.to_string(),
        );
    }
    Ok(contents)
}

/// `.wt.env` is written for process ports, and whenever the repository's
/// `.envrc` loads it: direnv then exports every leased port last, so values
/// from user-wide env files cannot shadow the worktree's ports.
fn writes_process_env(config: &Config, source: &Path, assignments: &[Assignment]) -> bool {
    if assignments.is_empty() {
        return false;
    }
    assignments.iter().any(|assignment| assignment.process)
        || (config.env.is_some()
            && fs::read_to_string(source.join(".envrc"))
                .is_ok_and(|contents| contents.contains(PROCESS_ENV)))
}

fn write_process_env(
    target: &Path,
    assignments: &[Assignment],
    compose_name: Option<&str>,
) -> Result<()> {
    let mut contents = String::from("# Generated by wt. Do not edit.\n");
    for assignment in assignments {
        contents.push_str(&format!("{}={}\n", assignment.key, assignment.assigned));
    }
    if let Some(name) = compose_name {
        contents.push_str(&format!("COMPOSE_PROJECT_NAME={name}\n"));
    }
    fs::write(target.join(PROCESS_ENV), contents).context("write .wt.env")
}

/// Lets direnv load the worktree's `.envrc` when it is byte-identical to the
/// checkout's `.envrc` that direnv already allows. Nothing new is trusted.
pub fn allow_direnv(source: &Path, target: &Path) -> Result<bool> {
    let envrc = target.join(".envrc");
    if !envrc.is_file() {
        return Ok(false);
    }
    if fs::read(&envrc)? != fs::read(source.join(".envrc")).unwrap_or_default() {
        return Ok(false);
    }
    if direnv_allowed(source)? != Some(true) {
        return Ok(false);
    }
    let output = Command::new("direnv")
        .current_dir(target)
        .args(["allow", "."])
        .output()
        .context("run direnv allow")?;
    if !output.status.success() {
        bail!(
            "direnv allow failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(true)
}

/// Whether direnv allows the `.envrc` in `directory`; `None` when direnv is
/// not installed or reports no `.envrc`.
pub fn direnv_allowed(directory: &Path) -> Result<Option<bool>> {
    let Ok(output) = Command::new("direnv")
        .current_dir(directory)
        .arg("status")
        .output()
    else {
        return Ok(None);
    };
    if !output.status.success() {
        return Ok(None);
    }
    let status = String::from_utf8_lossy(&output.stdout);
    Ok(status.lines().find_map(|line| {
        line.trim()
            .strip_prefix("Found RC allowed ")
            .map(|code| code.trim() == "0")
    }))
}

fn value<'a>(contents: &'a str, key: &str) -> Option<&'a str> {
    contents.lines().find_map(|line| {
        let line = line
            .trim_start()
            .strip_prefix("export ")
            .unwrap_or(line.trim_start());
        line.strip_prefix(key)?
            .strip_prefix('=')
            .map(|value| value.trim())
    })
}

fn replace_value(contents: &str, key: &str, new_value: &str) -> String {
    let prefix = format!("{key}=");
    contents
        .lines()
        .map(|line| {
            line.strip_prefix(&prefix)
                .map_or_else(|| line.to_owned(), |_| format!("{prefix}{new_value}"))
        })
        .collect::<Vec<_>>()
        .join("\n")
        + if contents.ends_with('\n') { "\n" } else { "" }
}

fn set_value(path: &Path, key: &str, new_value: &str) -> Result<()> {
    let mut updated = fs::read_to_string(path)?;
    if value(&updated, key).is_some() {
        updated = replace_value(&updated, key, new_value);
    } else {
        if !updated.is_empty() && !updated.ends_with('\n') {
            updated.push('\n');
        }
        updated.push_str(&format!("{key}={new_value}\n"));
    }
    fs::write(path, updated)?;
    Ok(())
}

fn fingerprints(target: &Path, paths: &[PathBuf]) -> Result<BTreeMap<PathBuf, String>> {
    paths
        .iter()
        .map(|path| Ok((path.clone(), fingerprint(target, path)?)))
        .collect()
}

/// Content hash of a managed file, or `link:<target>` for a shared symlink.
pub fn fingerprint(root: &Path, path: &Path) -> Result<String> {
    let metadata = fs::symlink_metadata(root.join(path))?;
    if metadata.file_type().is_symlink() {
        return Ok(format!(
            "link:{}",
            fs::read_link(root.join(path))?.display()
        ));
    }
    if !metadata.is_file() {
        bail!("changed managed file: {}", path.display());
    }
    let output = Command::new("git")
        .current_dir(root)
        .args(["hash-object", "--no-filters"])
        .arg(path)
        .output()?;
    if !output.status.success() {
        bail!("cannot fingerprint {}", path.display());
    }
    Ok(String::from_utf8(output.stdout)?.trim().to_owned())
}

pub fn discover_ports(path: &Path) -> Result<Vec<String>> {
    let contents = fs::read_to_string(path)?;
    Ok(contents
        .lines()
        .filter_map(|line| {
            let (key, value) = line.split_once('=')?;
            (key.ends_with("PORT") && value.trim().parse::<u16>().is_ok()).then(|| key.to_owned())
        })
        .collect())
}
